const express = require("express")
const router = express.Router()
const auth = require('../middleware/auth')
const tripController = require("../controller/tripController")
router.post("/trip",auth,tripController.addTrip)
router.get("/trip",auth,tripController.findTrip)
router.get("/trip/:_id",tripController.findTripById)
router.get("/findTripByUserId/:user_id",tripController.findTripByUserId)
router.delete("/trip/:_id",tripController.deleteTripById)
router.put("/trip/:_id",tripController.updateTrip)
router.get("/search",tripController.searchTrip)
module.exports = router