const express = require("express")
const router = express.Router()
const auth = require('../middleware/auth')
const tripController = require("../controller/tripController")
router.post("/createTrip",auth,tripController.addTrip)
router.get("/findTrip",tripController.findTrip)
router.get("/findTripById/:_id",tripController.findTripById)
router.get("/findTripByUserId/:user_id",auth,tripController.findTripByUserId)
router.delete("/deleteTrip/:_id",tripController.deleteTripById)
router.put("/updateTrip/:_id",tripController.updateTrip)
module.exports = router